FROM tamil-dictionary:latest AS base

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.1.0 /lambda-adapter /opt/extensions/lambda-adapter

ARG RES_BASE_PATH := "/res/"

ENV RES_BASE_PATH=${RES_BASE_PATH}

ENV ROCKET_ADDRESS=127.0.0.1
ENV ROCKET_PORT=8080

ENV AWS_LWA_READINESS_CHECK_PATH=/api/health
ENV AWS_LWA_READINESS_CHECK_HEALTHY_STATUS=200
